/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteImport } from './routes/unauthenticated'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CssModulesDemoRouteImport } from './routes/css-modules-demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardPreviewRouteImport } from './routes/dashboard/preview'
import { Route as DashboardFramesRouteImport } from './routes/dashboard/frames'
import { Route as DashboardFigmaRouteImport } from './routes/dashboard/figma'
import { Route as DashboardDesignPreviewRouteImport } from './routes/dashboard/design-preview'
import { Route as ProfileUserIdIndexRouteImport } from './routes/profile/$userId/index'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiFigmaCallbackRouteImport } from './routes/api/figma/callback'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/unauthenticated',
  path: '/unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CssModulesDemoRoute = CssModulesDemoRouteImport.update({
  id: '/css-modules-demo',
  path: '/css-modules-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPreviewRoute = DashboardPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFramesRoute = DashboardFramesRouteImport.update({
  id: '/frames',
  path: '/frames',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFigmaRoute = DashboardFigmaRouteImport.update({
  id: '/figma',
  path: '/figma',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDesignPreviewRoute = DashboardDesignPreviewRouteImport.update({
  id: '/design-preview',
  path: '/design-preview',
  getParentRoute: () => DashboardRoute,
} as any)
const ProfileUserIdIndexRoute = ProfileUserIdIndexRouteImport.update({
  id: '/profile/$userId/',
  path: '/profile/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFigmaCallbackRoute = ApiFigmaCallbackRouteImport.update({
  id: '/api/figma/callback',
  path: '/api/figma/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/css-modules-demo': typeof CssModulesDemoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/dashboard/design-preview': typeof DashboardDesignPreviewRoute
  '/dashboard/figma': typeof DashboardFigmaRoute
  '/dashboard/frames': typeof DashboardFramesRoute
  '/dashboard/preview': typeof DashboardPreviewRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/figma/callback': typeof ApiFigmaCallbackRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/profile/$userId/': typeof ProfileUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/css-modules-demo': typeof CssModulesDemoRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/dashboard/design-preview': typeof DashboardDesignPreviewRoute
  '/dashboard/figma': typeof DashboardFigmaRoute
  '/dashboard/frames': typeof DashboardFramesRoute
  '/dashboard/preview': typeof DashboardPreviewRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/figma/callback': typeof ApiFigmaCallbackRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/profile/$userId': typeof ProfileUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/css-modules-demo': typeof CssModulesDemoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/dashboard/design-preview': typeof DashboardDesignPreviewRoute
  '/dashboard/figma': typeof DashboardFigmaRoute
  '/dashboard/frames': typeof DashboardFramesRoute
  '/dashboard/preview': typeof DashboardPreviewRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/figma/callback': typeof ApiFigmaCallbackRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/profile/$userId/': typeof ProfileUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/css-modules-demo'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/unauthenticated'
    | '/dashboard/design-preview'
    | '/dashboard/figma'
    | '/dashboard/frames'
    | '/dashboard/preview'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/figma/callback'
    | '/api/stripe/webhook'
    | '/profile/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/css-modules-demo'
    | '/sign-in'
    | '/sign-up'
    | '/unauthenticated'
    | '/dashboard/design-preview'
    | '/dashboard/figma'
    | '/dashboard/frames'
    | '/dashboard/preview'
    | '/dashboard/settings'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/figma/callback'
    | '/api/stripe/webhook'
    | '/profile/$userId'
  id:
    | '__root__'
    | '/'
    | '/css-modules-demo'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/unauthenticated'
    | '/dashboard/design-preview'
    | '/dashboard/figma'
    | '/dashboard/frames'
    | '/dashboard/preview'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/figma/callback'
    | '/api/stripe/webhook'
    | '/profile/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CssModulesDemoRoute: typeof CssModulesDemoRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  UnauthenticatedRoute: typeof UnauthenticatedRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFigmaCallbackRoute: typeof ApiFigmaCallbackRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ProfileUserIdIndexRoute: typeof ProfileUserIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthenticated': {
      id: '/unauthenticated'
      path: '/unauthenticated'
      fullPath: '/unauthenticated'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css-modules-demo': {
      id: '/css-modules-demo'
      path: '/css-modules-demo'
      fullPath: '/css-modules-demo'
      preLoaderRoute: typeof CssModulesDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/preview': {
      id: '/dashboard/preview'
      path: '/preview'
      fullPath: '/dashboard/preview'
      preLoaderRoute: typeof DashboardPreviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/frames': {
      id: '/dashboard/frames'
      path: '/frames'
      fullPath: '/dashboard/frames'
      preLoaderRoute: typeof DashboardFramesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/figma': {
      id: '/dashboard/figma'
      path: '/figma'
      fullPath: '/dashboard/figma'
      preLoaderRoute: typeof DashboardFigmaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/design-preview': {
      id: '/dashboard/design-preview'
      path: '/design-preview'
      fullPath: '/dashboard/design-preview'
      preLoaderRoute: typeof DashboardDesignPreviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/profile/$userId/': {
      id: '/profile/$userId/'
      path: '/profile/$userId'
      fullPath: '/profile/$userId/'
      preLoaderRoute: typeof ProfileUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/figma/callback': {
      id: '/api/figma/callback'
      path: '/api/figma/callback'
      fullPath: '/api/figma/callback'
      preLoaderRoute: typeof ApiFigmaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardDesignPreviewRoute: typeof DashboardDesignPreviewRoute
  DashboardFigmaRoute: typeof DashboardFigmaRoute
  DashboardFramesRoute: typeof DashboardFramesRoute
  DashboardPreviewRoute: typeof DashboardPreviewRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDesignPreviewRoute: DashboardDesignPreviewRoute,
  DashboardFigmaRoute: DashboardFigmaRoute,
  DashboardFramesRoute: DashboardFramesRoute,
  DashboardPreviewRoute: DashboardPreviewRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CssModulesDemoRoute: CssModulesDemoRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  UnauthenticatedRoute: UnauthenticatedRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFigmaCallbackRoute: ApiFigmaCallbackRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ProfileUserIdIndexRoute: ProfileUserIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
